services:
  gsplot:
    restart: always
    build: .
    container_name: 'gsplot'
    working_dir: '/root/'
    tty: true
    environment:
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/opt
    ports:
      - "8000:8000"
