"""Distribution metadata compatibility values.

The ``__version__`` value is owned by the distribution metadata in
``pyproject.toml``.  The ``__commit__`` compatibility value is always ``None``
unless a future public build contract changes it.  This module remains as a
small compatibility surface for existing imports; it is not generated by a
workflow and never embeds a repository commit hash.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version


def _installed_version() -> str:
    """Return the installed distribution version or a source-tree fallback."""

    try:
        return version("gsplot")
    except PackageNotFoundError:
        return "0+unknown"


__version__: str = _installed_version()
__commit__: str | None = None
