"""Private, side-effect-free foundations for the canonical API."""

from .errors import (
    ConfigError,
    DataError,
    GsplotError,
    LayoutError,
    MetadataError,
    OutputError,
    PlotError,
)
from .numerics import as_float_array, segment_points, validate_color_values, validate_xy
from .types import (
    AxesTarget,
    AxisSpec,
    BuildInfo,
    ColorSpec,
    InsetSpec,
    LegendEntries,
    MetadataSnapshot,
    MosaicSpec,
    NormalizeSpec,
    PerTarget,
    RGBColor,
    Theme,
)
from .validation import (
    MISSING,
    ensure_bool,
    ensure_finite_real,
    ensure_iterable,
    ensure_mapping,
    ensure_nonempty_text,
    ensure_nonnegative,
    ensure_pair,
    ensure_positive,
    reject_unknown_keys,
    resolve_option,
)

__all__ = [
    "GsplotError",
    "ConfigError",
    "DataError",
    "LayoutError",
    "PlotError",
    "OutputError",
    "MetadataError",
    "RGBColor",
    "ColorSpec",
    "MosaicSpec",
    "AxesTarget",
    "PerTarget",
    "NormalizeSpec",
    "AxisSpec",
    "InsetSpec",
    "Theme",
    "MetadataSnapshot",
    "BuildInfo",
    "LegendEntries",
    "MISSING",
    "resolve_option",
    "ensure_finite_real",
    "ensure_positive",
    "ensure_nonnegative",
    "ensure_pair",
    "reject_unknown_keys",
    "ensure_mapping",
    "ensure_nonempty_text",
    "ensure_bool",
    "ensure_iterable",
    "as_float_array",
    "validate_xy",
    "validate_color_values",
    "segment_points",
]
