# .github/workflows/build.yml
name: Build and Save Version Info

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.2.0

      - name: Install dependencies
        run: poetry install --no-root

      - name: Get Git commit hash
        run: echo "COMMIT_HASH=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Get package version
        run: |
          VERSION=$(poetry version -s)
          echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Write version info to file
        run: |
          echo "__version__ = '${{ env.PACKAGE_VERSION }}'" > gsplot/gsplot/version.py
          echo "__commit__ = '${{ env.COMMIT_HASH }}'" >> gsplot/gsplot/version.py

      - name: Build package
        run: poetry build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*

