# .github/workflows/build.yml
name: Build and Save Version Info

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.2.0

      - name: Install dependencies
        run: poetry install --no-root

      - name: Get Git commit hash
        run: echo "COMMIT_HASH=${GITHUB_SHA}" >> "$GITHUB_ENV"


      - name: Get package version
        run: |
          VERSION="$(poetry version -s)"
          echo "PACKAGE_VERSION=${VERSION}" >> "$GITHUB_ENV"

      - name: Write version info to file
        run: |
          echo "__version__ = '${{ env.PACKAGE_VERSION }}'" > gsplot/version.py
          echo "__commit__ = '${{ env.COMMIT_HASH }}'" >> gsplot/version.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update version.py with build information"
          add: "gsplot/version.py"

      - name: Build package
        run: poetry build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

